### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by bluecamel** [clydemcqueen/tello_ros#50]
Thank you so much for this great project!

I just wanted to thank you and share a project that I made this weekend: [tello_ros_docker](https://github.com/bluecamel/tello_ros_docker).  It creates a docker image to run tello_ros.  Right now, it's not completely setup to work with a real Tello drone (I don't have one yet, but should be getting one this week).  So, for the moment, it defaults to running the tello_gazebo simple_launch.

Anyhow, it should be a useful development environment for others or even just a quick way to get tello_ros running.  If you're interested in taking a look, I'd welcome any feedback.

**Comment by clydemcqueen** [comment]
@bluecamel Hey, that's great! Honestly I have zero experience with docker, so I can't provide any feedback. But I imagine that others will appreciate how quickly you can get set up & flying.

**Comment by bluecamel** [comment]
One of my goals is to make this easy for folks with zero docker experience.  I'm not quite there yet, but I'll keep improving it.  I got a Tello and have updated the project to work with both tello_driver and tello_gazebo :)

Anyhow, I'll close this and leave you alone, but looking forward to using this project a lot more!
