### ISSUE TITLE
Install ROS 2 to tello

### ISSUE THREAD

**Issue by cholazzzb** [clydemcqueen/tello_ros#59]
Hello, I am still in Tello and ROS 2. I want to buy 2 tellos and build swarm controller. Before I buy it, I have a question, how to install ROS 2 in tello and use this repo as a driver? Will I buy Raspberry Phi and attach it on tello? Thank you

**Comment by tentone** [comment]
Hello

You are not expected to install anything into the tello itself. You can install ROS 2 into any computer (a raspberry pi will do). The drone will then communicate with this programing via wifi. So the drone is remotely controlled.

**Comment by cholazzzb** [comment]
Okay Thank you for your answer @tentone
