### ISSUE TITLE
Camera does not work in rviz2 with Gazebo.

### ISSUE THREAD

**Issue by emad555** [clydemcqueen/tello_ros#60]
The camera topic does not display any information in rviz2

**Comment by clydemcqueen** [comment]
I assume that you're running `ros2 launch tello_gazebo simple_launch.py` with Foxy + Gazebo 11. I can see the simulated camera in rviz2 with these settings (note the `Best Effort` setting):
![image](https://user-images.githubusercontent.com/4961326/115798763-da1c4700-a38b-11eb-86a9-5827dba45f1f.png)

**Comment by EddieMG** [comment]
@emad555 I believe you run into the same problem as me, if you are using the Docker file, you may be encountering this [issue](https://answers.ros.org/question/313761/camera-plugin-failed-to-load-on-crystal/).

I solved it by manually installing `sudo apt install ros-foxy-gazebo-ros-pkgs`. It seems its a common issue [i.e.](https://github.com/szebedy/autonomous-drone/issues/7).

 @clydemcqueen  Great work btw.

**Comment by clydemcqueen** [comment]
Ah, thanks for the insight @EddieMG 

I will add `<exec_depend>gazebo_ros_pkgs</exec_depend>` to the package.xml file so rosdep picks it up.

**Comment by cncowboy** [comment]
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins/
can resolve this issue
