### ISSUE TITLE
Cite your plugin in scientific paper

### ISSUE THREAD

**Issue by KiloNovemberDelta** [clydemcqueen/tello_ros#71]
Hello,
Thank you for your open-source plugin, which was quite useful to simulate and control Tello through ROS2. 
I want to acknowledge your work by citing you in my scientific article. Do you have any reference that I can cite? 
Have a good day

**Comment by clydemcqueen** [comment]
Hi @KiloNovemberDelta

I am glad that is has been useful! Thank you for the kind words.

I added a CITATION.cff file with the author names. I may update a bit, but will merge soon.

/Clyde
