### ISSUE TITLE
Error while doung Colcon Build: Permission denied

### ISSUE THREAD

**Issue by mich1342** [clydemcqueen/tello_ros#78]
Hi, I am trying to colcon build using Ubuntu 22.04 and ROS2 Humble. I got error for the /tello_description/src/replace.py: Permission denied.

I have tried adding sudo to the colcon build but still the same

**Comment by TiNovosel** [comment]
Just give a permission with:
chmod +x /home/{username}/tello_ros_ws/src/tello_ros/tello_description/src/replace.py

**Comment by mich1342** [comment]
hi @TiNovosel,

Thank you. It works for me.
